version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      - npm install @ionic/cli
      - npm install cordova
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Building...
      - CI='' npm run build:prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build